version: "3.9"
services:
  app:
    build: .
    container_name: aai-app
    restart: unless-stopped
    ports:
      - "8787:8787"
    env_file:
      - .env
    volumes:
      - ./server/data.sqlite:/app/server/data.sqlite
